### ISSUE TITLE
Which version of web3 should I use?

### ISSUE THREAD

**Issue by dcb9** [ConnextProject/connext-client#145]
I have tried version `1.0.0-beta.36`.  when I opening a thread, it occurs the error 'Uncaught (in promise) Error: Returned error: Method personal_sign not supported.'

I noticed that I can pass the Web3 Lib to the connext here
https://github.com/ConnextProject/connext-client/blob/dc23d7614bae27cbec22c3d796d6076259d7724c/src/Connext.js#L299-L311

[web3.eth.personal.sign gives error Unhandled rejection Error: Returned error: Method not found](https://github.com/ethereum/web3.js/issues/1220)

**Comment by LayneHaber** [comment]
You should be using the latest version of web3, instantiate it, and pass in the instantiated version to the client package in the constructor params.

Let me know if that worked for you.

**Comment by dcb9** [comment]
It's still not work, btw my connext version is `2.5.10`

```js
    const hubAddress = "0xcd145c1fcc13bff93fcf329b614071bc68e24034"
    const web3 = new Web3("http://localhost:8545")
    const connext = new Connext({
      web3,
      hubUrl: "http://localhost:3000",
      hubAddress,
      contractAddress: "0xeb85d2df434d660b23a3dcbc00f8fa7f080d3139",
    }, Web3)
    console.log("web3.version:",web3.version) // output: web3.version 1.0.0-beta.36
```

**Comment by LayneHaber** [comment]
Thats the right version for the beta, you shouldn't need to actually pass in the Web3 library when you are instantiating the client, so try this: 
```javascript
const hubAddress = "0xcd145c1fcc13bff93fcf329b614071bc68e24034"
const web3 = new Web3("http://localhost:8545")
const connext = new Connext({
      web3,
      hubUrl: "http://localhost:3000",
      hubAddress,
      contractAddress: "0xeb85d2df434d660b23a3dcbc00f8fa7f080d3139",
    })
```

Will look into this and try to recreate, in the meantime you can jump into our [discord dev chat](https://discord.gg/v5Urgv2) for more help.

**Comment by hthillman** [comment]
@dcb9 did this work?

**Comment by dcb9** [comment]
I copied `getWeb3.js` from payment-starter-kit, then it works.

```js
import getWeb3 from './utils/getWeb3'
const web3 = await getWeb3()
```

**Comment by hthillman** [comment]
Awesome. Feel free to join our Discord (https://discord.gg/yKkzZZm) if you haven't already, would love to hear more about what you're doing and answer any questions that come up.
